//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class addrfeat
    {
        public int gid { get; set; }
        public Nullable<long> tlid { get; set; }
        public string statefp { get; set; }
        public string aridl { get; set; }
        public string aridr { get; set; }
        public string linearid { get; set; }
        public string fullname { get; set; }
        public string lfromhn { get; set; }
        public string ltohn { get; set; }
        public string rfromhn { get; set; }
        public string rtohn { get; set; }
        public string zipl { get; set; }
        public string zipr { get; set; }
        public string edge_mtfcc { get; set; }
        public string parityl { get; set; }
        public string parityr { get; set; }
        public string plus4l { get; set; }
        public string plus4r { get; set; }
        public string lfromtyp { get; set; }
        public string ltotyp { get; set; }
        public string rfromtyp { get; set; }
        public string rtotyp { get; set; }
        public string offsetl { get; set; }
        public string offsetr { get; set; }
    }
}
