//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class county
    {
        public int gid { get; set; }
        public string statefp { get; set; }
        public string countyfp { get; set; }
        public string countyns { get; set; }
        public string cntyidfp { get; set; }
        public string name { get; set; }
        public string namelsad { get; set; }
        public string lsad { get; set; }
        public string classfp { get; set; }
        public string mtfcc { get; set; }
        public string csafp { get; set; }
        public string cbsafp { get; set; }
        public string metdivfp { get; set; }
        public string funcstat { get; set; }
        public Nullable<long> aland { get; set; }
        public Nullable<double> awater { get; set; }
        public string intptlat { get; set; }
        public string intptlon { get; set; }
    }
}
