//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class edge
    {
        public int gid { get; set; }
        public string statefp { get; set; }
        public string countyfp { get; set; }
        public Nullable<long> tlid { get; set; }
        public Nullable<decimal> tfidl { get; set; }
        public Nullable<decimal> tfidr { get; set; }
        public string mtfcc { get; set; }
        public string fullname { get; set; }
        public string smid { get; set; }
        public string lfromadd { get; set; }
        public string ltoadd { get; set; }
        public string rfromadd { get; set; }
        public string rtoadd { get; set; }
        public string zipl { get; set; }
        public string zipr { get; set; }
        public string featcat { get; set; }
        public string hydroflg { get; set; }
        public string railflg { get; set; }
        public string roadflg { get; set; }
        public string olfflg { get; set; }
        public string passflg { get; set; }
        public string divroad { get; set; }
        public string exttyp { get; set; }
        public string ttyp { get; set; }
        public string deckedroad { get; set; }
        public string artpath { get; set; }
        public string persist { get; set; }
        public string gcseflg { get; set; }
        public string offsetl { get; set; }
        public string offsetr { get; set; }
        public Nullable<decimal> tnidf { get; set; }
        public Nullable<decimal> tnidt { get; set; }
    }
}
