//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class face
    {
        public int gid { get; set; }
        public Nullable<decimal> tfid { get; set; }
        public string statefp00 { get; set; }
        public string countyfp00 { get; set; }
        public string tractce00 { get; set; }
        public string blkgrpce00 { get; set; }
        public string blockce00 { get; set; }
        public string cousubfp00 { get; set; }
        public string submcdfp00 { get; set; }
        public string conctyfp00 { get; set; }
        public string placefp00 { get; set; }
        public string aiannhfp00 { get; set; }
        public string aiannhce00 { get; set; }
        public string comptyp00 { get; set; }
        public string trsubfp00 { get; set; }
        public string trsubce00 { get; set; }
        public string anrcfp00 { get; set; }
        public string elsdlea00 { get; set; }
        public string scsdlea00 { get; set; }
        public string unsdlea00 { get; set; }
        public string uace00 { get; set; }
        public string cd108fp { get; set; }
        public string sldust00 { get; set; }
        public string sldlst00 { get; set; }
        public string vtdst00 { get; set; }
        public string zcta5ce00 { get; set; }
        public string tazce00 { get; set; }
        public string ugace00 { get; set; }
        public string puma5ce00 { get; set; }
        public string statefp { get; set; }
        public string countyfp { get; set; }
        public string tractce { get; set; }
        public string blkgrpce { get; set; }
        public string blockce { get; set; }
        public string cousubfp { get; set; }
        public string submcdfp { get; set; }
        public string conctyfp { get; set; }
        public string placefp { get; set; }
        public string aiannhfp { get; set; }
        public string aiannhce { get; set; }
        public string comptyp { get; set; }
        public string trsubfp { get; set; }
        public string trsubce { get; set; }
        public string anrcfp { get; set; }
        public string ttractce { get; set; }
        public string tblkgpce { get; set; }
        public string elsdlea { get; set; }
        public string scsdlea { get; set; }
        public string unsdlea { get; set; }
        public string uace { get; set; }
        public string cd111fp { get; set; }
        public string sldust { get; set; }
        public string sldlst { get; set; }
        public string vtdst { get; set; }
        public string zcta5ce { get; set; }
        public string tazce { get; set; }
        public string ugace { get; set; }
        public string puma5ce { get; set; }
        public string csafp { get; set; }
        public string cbsafp { get; set; }
        public string metdivfp { get; set; }
        public string cnectafp { get; set; }
        public string nectafp { get; set; }
        public string nctadvfp { get; set; }
        public string lwflag { get; set; }
        public string offset { get; set; }
        public Nullable<double> atotal { get; set; }
        public string intptlat { get; set; }
        public string intptlon { get; set; }
    }
}
