//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class featname
    {
        public int gid { get; set; }
        public Nullable<long> tlid { get; set; }
        public string fullname { get; set; }
        public string name { get; set; }
        public string predirabrv { get; set; }
        public string pretypabrv { get; set; }
        public string prequalabr { get; set; }
        public string sufdirabrv { get; set; }
        public string suftypabrv { get; set; }
        public string sufqualabr { get; set; }
        public string predir { get; set; }
        public string pretyp { get; set; }
        public string prequal { get; set; }
        public string sufdir { get; set; }
        public string suftyp { get; set; }
        public string sufqual { get; set; }
        public string linearid { get; set; }
        public string mtfcc { get; set; }
        public string paflag { get; set; }
        public string statefp { get; set; }
    }
}
