//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class layer
    {
        public int topology_id { get; set; }
        public int layer_id { get; set; }
        public string schema_name { get; set; }
        public string table_name { get; set; }
        public string feature_column { get; set; }
        public int feature_type { get; set; }
        public int level { get; set; }
        public Nullable<int> child_id { get; set; }
    
        public virtual topology topology { get; set; }
    }
}
