//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class loader_lookuptables
    {
        public int process_order { get; set; }
        public string lookup_name { get; set; }
        public string table_name { get; set; }
        public bool single_mode { get; set; }
        public bool load { get; set; }
        public bool level_county { get; set; }
        public bool level_state { get; set; }
        public bool level_nation { get; set; }
        public string post_load_process { get; set; }
        public Nullable<bool> single_geom_mode { get; set; }
        public string insert_mode { get; set; }
        public string pre_load_process { get; set; }
        public string website_root_override { get; set; }
    }
}
