//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class loader_variables
    {
        public string tiger_year { get; set; }
        public string website_root { get; set; }
        public string staging_fold { get; set; }
        public string data_schema { get; set; }
        public string staging_schema { get; set; }
    }
}
