//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class loader_platform
    {
        public string os { get; set; }
        public string declare_sect { get; set; }
        public string pgbin { get; set; }
        public string wget { get; set; }
        public string unzip_command { get; set; }
        public string psql { get; set; }
        public string path_sep { get; set; }
        public string loader { get; set; }
        public string environ_set_command { get; set; }
        public string county_process_command { get; set; }
    }
}
