//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagc_gaz
    {
        public int id { get; set; }
        public Nullable<int> seq { get; set; }
        public string word { get; set; }
        public string stdword { get; set; }
        public Nullable<int> token { get; set; }
        public bool is_custom { get; set; }
    }
}
