//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class qms_seat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qms_seat()
        {
            this.qms_queue = new HashSet<qms_queue>();
        }
    
        public int seat_id { get; set; }
        public int service_id { get; set; }
        public int seat_number { get; set; }
        public int assigned_id { get; set; }
        public System.DateTime created_date { get; set; }
        public System.DateTime modified_date { get; set; }
        public bool active { get; set; }
        public int modified_by { get; set; }
    
        public virtual appuser appuser { get; set; }
        public virtual appuser appuser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qms_queue> qms_queue { get; set; }
        public virtual qms_service qms_service { get; set; }
    }
}
