//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class qms_queue
    {
        public int queue_id { get; set; }
        public int service_id { get; set; }
        public int queue_number { get; set; }
        public Nullable<int> assigned_id { get; set; }
        public System.DateTime created_date { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string queue_status { get; set; }
        public bool called { get; set; }
        public Nullable<System.DateTime> call_date { get; set; }
        public Nullable<int> seat_id { get; set; }
    
        public virtual appuser appuser { get; set; }
        public virtual qms_queue_status qms_queue_status { get; set; }
        public virtual qms_seat qms_seat { get; set; }
        public virtual qms_service qms_service { get; set; }
    }
}
