//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class qms_service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qms_service()
        {
            this.qms_queue = new HashSet<qms_queue>();
            this.qms_seat = new HashSet<qms_seat>();
        }
    
        public int service_id { get; set; }
        public string service_type { get; set; }
        public string region_code { get; set; }
        public System.DateTime created_date { get; set; }
        public bool active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qms_queue> qms_queue { get; set; }
        public virtual qms_region qms_region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qms_seat> qms_seat { get; set; }
        public virtual qms_service_type qms_service_type { get; set; }
    }
}
