//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QmsdbEntities : DbContext
    {
        public QmsdbEntities()
            : base("name=QmsdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<access_rules> access_rules { get; set; }
        public virtual DbSet<appuser> appusers { get; set; }
        public virtual DbSet<lkp_state> lkp_state { get; set; }
        public virtual DbSet<location_type_upper> location_type_upper { get; set; }
        public virtual DbSet<logger> loggers { get; set; }
        public virtual DbSet<pointcloud_formats> pointcloud_formats { get; set; }
        public virtual DbSet<setting> settings { get; set; }
        public virtual DbSet<spatial_ref_sys> spatial_ref_sys { get; set; }
        public virtual DbSet<qms_queue> qms_queue { get; set; }
        public virtual DbSet<qms_queue_status> qms_queue_status { get; set; }
        public virtual DbSet<qms_region> qms_region { get; set; }
        public virtual DbSet<qms_seat> qms_seat { get; set; }
        public virtual DbSet<qms_service> qms_service { get; set; }
        public virtual DbSet<qms_service_type> qms_service_type { get; set; }
        public virtual DbSet<qms_setting> qms_setting { get; set; }
        public virtual DbSet<addr> addrs { get; set; }
        public virtual DbSet<addrfeat> addrfeats { get; set; }
        public virtual DbSet<bg> bgs { get; set; }
        public virtual DbSet<county> counties { get; set; }
        public virtual DbSet<county_lookup> county_lookup { get; set; }
        public virtual DbSet<countysub_lookup> countysub_lookup { get; set; }
        public virtual DbSet<cousub> cousubs { get; set; }
        public virtual DbSet<direction_lookup> direction_lookup { get; set; }
        public virtual DbSet<edge> edges { get; set; }
        public virtual DbSet<face> faces { get; set; }
        public virtual DbSet<featname> featnames { get; set; }
        public virtual DbSet<geocode_settings> geocode_settings { get; set; }
        public virtual DbSet<geocode_settings_default> geocode_settings_default { get; set; }
        public virtual DbSet<loader_lookuptables> loader_lookuptables { get; set; }
        public virtual DbSet<loader_platform> loader_platform { get; set; }
        public virtual DbSet<loader_variables> loader_variables { get; set; }
        public virtual DbSet<pagc_gaz> pagc_gaz { get; set; }
        public virtual DbSet<pagc_lex> pagc_lex { get; set; }
        public virtual DbSet<pagc_rules> pagc_rules { get; set; }
        public virtual DbSet<place> places { get; set; }
        public virtual DbSet<place_lookup> place_lookup { get; set; }
        public virtual DbSet<secondary_unit_lookup> secondary_unit_lookup { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<state_lookup> state_lookup { get; set; }
        public virtual DbSet<street_type_lookup> street_type_lookup { get; set; }
        public virtual DbSet<tabblock> tabblocks { get; set; }
        public virtual DbSet<tabblock20> tabblock20 { get; set; }
        public virtual DbSet<tract> tracts { get; set; }
        public virtual DbSet<zcta5> zcta5 { get; set; }
        public virtual DbSet<zip_lookup> zip_lookup { get; set; }
        public virtual DbSet<zip_lookup_base> zip_lookup_base { get; set; }
        public virtual DbSet<zip_state> zip_state { get; set; }
        public virtual DbSet<zip_state_loc> zip_state_loc { get; set; }
        public virtual DbSet<layer> layers { get; set; }
        public virtual DbSet<topology> topologies { get; set; }
    }
}
