//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class spatial_ref_sys
    {
        public int srid { get; set; }
        public string auth_name { get; set; }
        public Nullable<int> auth_srid { get; set; }
        public string srtext { get; set; }
        public string proj4text { get; set; }
    }
}
