//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public int gid { get; set; }
        public string region { get; set; }
        public string division { get; set; }
        public string statefp { get; set; }
        public string statens { get; set; }
        public string stusps { get; set; }
        public string name { get; set; }
        public string lsad { get; set; }
        public string mtfcc { get; set; }
        public string funcstat { get; set; }
        public Nullable<long> aland { get; set; }
        public Nullable<long> awater { get; set; }
        public string intptlat { get; set; }
        public string intptlon { get; set; }
    }
}
