//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabblock20
    {
        public string statefp { get; set; }
        public string countyfp { get; set; }
        public string tractce { get; set; }
        public string blockce { get; set; }
        public string geoid { get; set; }
        public string name { get; set; }
        public string mtfcc { get; set; }
        public string ur { get; set; }
        public string uace { get; set; }
        public string uatype { get; set; }
        public string funcstat { get; set; }
        public Nullable<double> aland { get; set; }
        public Nullable<double> awater { get; set; }
        public string intptlat { get; set; }
        public string intptlon { get; set; }
    }
}
