//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class zcta5
    {
        public int gid { get; set; }
        public string statefp { get; set; }
        public string zcta5ce { get; set; }
        public string classfp { get; set; }
        public string mtfcc { get; set; }
        public string funcstat { get; set; }
        public Nullable<double> aland { get; set; }
        public Nullable<double> awater { get; set; }
        public string intptlat { get; set; }
        public string intptlon { get; set; }
        public string partflg { get; set; }
    }
}
