//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class zip_lookup
    {
        public int zip { get; set; }
        public Nullable<int> st_code { get; set; }
        public string state { get; set; }
        public Nullable<int> co_code { get; set; }
        public string county { get; set; }
        public Nullable<int> cs_code { get; set; }
        public string cousub { get; set; }
        public Nullable<int> pl_code { get; set; }
        public string place { get; set; }
        public Nullable<int> cnt { get; set; }
    }
}
